### ISSUE TITLE
The porter crashes when loading 17boo mod

### ISSUE THREAD

**Issue by Willio2000** [gusborg88/fnf-porter#31]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Full mod

### What are the contents of the latest .log file? (if applicable)

09:10:27: [log.py:50] [INFO] Logger initialized!
09:10:27: [window.py:451] [INFO] Initiating window
09:10:56: [window.py:389] [WARNING] Folder C:/Users/willi/Downloads/funkin-windows-64bit/mods already existed before porting, files may have been overwritten.
09:10:56: [window.py:394] [INFO] Songs will be converted
09:10:56: [window.py:399] [INFO] Characters will be converted
09:10:56: [window.py:404] [INFO] Weeks will be converted
09:10:56: [main.py:50] [INFO] 
                 
=============================
    NEW CONVERSION STARTED
=============================
                
09:10:56: [main.py:57] [INFO] Converting started...
09:10:56: [main.py:58] [INFO] {'charts': True, 'songs': {'inst': True, 'voices': True, 'split': False}, 'characters': {'icons': True, 'json': True, 'assets': True}, 'weeks': {'props': True, 'levels': True, 'titles': True}, 'stages': True, 'modpack_meta': True, 'images': True}
09:10:56: [main.py:63] [INFO] Converting fromD:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo to C:/Users/willi/Downloads/funkin-windows-64bit/mods
09:10:56: [main.py:66] [INFO] Converting pack.json
09:10:56: [main.py:81] [WARNING] pack.json not found. Replaced it with default
09:10:56: [main.py:83] [INFO] Copying pack.png
09:10:56: [main.py:95] [WARNING] pack.png not found. Replacing it with default
09:10:56: [main.py:105] [INFO] Parsing and converting credits.txt
09:10:56: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data/*
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\66cute is a valid chart directory...
09:10:56: [main.py:130] [INFO] Loading charts in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\66cute
09:10:56: [ChartTools.py:37] [INFO] Initialising charts for 66cute...
09:10:56: [ChartTools.py:99] [INFO] Initialising metadata for 66Cute...
09:10:56: [ChartTools.py:34] [INFO] Chart for 66Cute was created!
09:10:56: [main.py:135] [INFO] Converting charts of D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\66cute...
09:10:56: [ChartTools.py:112] [INFO] Chart conversion for 66Cute started!
09:10:56: [ChartTools.py:173] [INFO] Chart conversion for 66Cute was completed!
09:10:56: [main.py:147] [INFO] D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\66cute charts converted, saving
09:10:56: [ChartTools.py:186] [INFO] [66cute] Saving 66Cute to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/songs/66cute
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\chars.hx is a valid chart directory...
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\credits.txt is a valid chart directory...
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\joner is a valid chart directory...
09:10:56: [main.py:130] [INFO] Loading charts in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\joner
09:10:56: [ChartTools.py:37] [INFO] Initialising charts for joner...
09:10:56: [ChartTools.py:50] [WARNING] [joner] events.json not supported yet! Sorry!
09:10:56: [ChartTools.py:99] [INFO] Initialising metadata for Joner...
09:10:56: [ChartTools.py:34] [INFO] Chart for Joner was created!
09:10:56: [main.py:135] [INFO] Converting charts of D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\joner...
09:10:56: [ChartTools.py:112] [INFO] Chart conversion for Joner started!
09:10:56: [ChartTools.py:173] [INFO] Chart conversion for Joner was completed!
09:10:56: [main.py:147] [INFO] D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\joner charts converted, saving
09:10:56: [ChartTools.py:186] [INFO] [joner] Saving Joner to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/songs/joner
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\ogg is a valid chart directory...
09:10:56: [main.py:130] [INFO] Loading charts in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\ogg
09:10:56: [ChartTools.py:37] [INFO] Initialising charts for ogg...
09:10:56: [ChartTools.py:99] [INFO] Initialising metadata for Ogg...
09:10:56: [ChartTools.py:34] [INFO] Chart for Ogg was created!
09:10:56: [main.py:135] [INFO] Converting charts of D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\ogg...
09:10:56: [ChartTools.py:112] [INFO] Chart conversion for Ogg started!
09:10:56: [ChartTools.py:173] [INFO] Chart conversion for Ogg was completed!
09:10:56: [main.py:147] [INFO] D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\ogg charts converted, saving
09:10:56: [ChartTools.py:186] [INFO] [ogg] Saving Ogg to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/songs/ogg
09:10:56: [main.py:128] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/data\readme.txt is a valid chart directory...
09:10:56: [main.py:153] [INFO] Copying character assets...
09:10:56: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters/*
09:10:56: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\666.png
09:10:56: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\666.xml
09:10:56: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\Datsalty.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\Datsalty.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\evlape.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\evlape.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\Headzo.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\Headzo.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\image.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\image.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\jank.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\jank.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\johndoe.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\johndoe.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\joner3.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\joner3.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\KEVINRX.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\KEVINRX.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\krollge.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\krollge.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\LEXRX.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\LEXRX.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\MIMIRX.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\MIMIRX.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\none.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\none.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\oliver.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\oliver.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\RBLXCYC.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\RBLXCYC.xml
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\readme.txt
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\zomb.png
09:10:57: [main.py:163] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/characters\zomb.xml
09:10:57: [main.py:175] [INFO] Converting character jsons...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters/*
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\666.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character 666.json
09:10:57: [CharacterTools.py:46] [INFO] [666] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': 'idle', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [666] Converting animation {'loop': False, 'offsets': [48, 36], 'anim': 'singUP', 'fps': 24, 'name': 'up', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [666] Converting animation {'loop': False, 'offsets': [20, -52], 'anim': 'singDOWN', 'fps': 24, 'name': 'down', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [666] Converting animation {'loop': False, 'offsets': [48, 3], 'anim': 'singLEFT', 'fps': 24, 'name': 'left', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [666] Converting animation {'offsets': [-53, -18], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [], 'name': 'right'}
09:10:57: [CharacterTools.py:51] [INFO] Character 666 successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/666.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\Datsalty.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character Datsalty.json
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'loop': False, 'offsets': [-30, 35], 'anim': 'singUP', 'fps': 24, 'name': 'johnup', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'loop': False, 'offsets': [0, -71], 'anim': 'singDOWN', 'fps': 24, 'name': 'johndown', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'loop': False, 'offsets': [50, -7], 'anim': 'singLEFT', 'fps': 24, 'name': 'johnleft', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'loop': False, 'offsets': [10, 29], 'anim': 'kill', 'fps': 24, 'name': 'johntransiiton', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [10, 90], 'loop': False, 'fps': 24, 'anim': 'singUP-alt', 'indices': [], 'name': 'john2up'}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [-60, 50], 'loop': False, 'fps': 24, 'anim': 'singRIGHT-alt', 'indices': [], 'name': 'john2right'}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [140, 20], 'loop': False, 'fps': 24, 'anim': 'singLEFT-alt', 'indices': [], 'name': 'john2left'}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [130, -70], 'loop': False, 'fps': 24, 'anim': 'singDOWN-alt', 'indices': [], 'name': 'john2down'}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [-23, -18], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [], 'name': 'johnright'}
09:10:57: [CharacterTools.py:46] [INFO] [Datsalty] Converting animation {'offsets': [0, 0], 'indices': [], 'fps': 24, 'anim': 'idle', 'loop': False, 'name': 'Datsalty'}
09:10:57: [CharacterTools.py:51] [INFO] Character Datsalty successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/Datsalty.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\evlape.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character evlape.json
09:10:57: [CharacterTools.py:46] [INFO] [Evlape] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'idle'}
09:10:57: [CharacterTools.py:46] [INFO] [Evlape] Converting animation {'offsets': [-100, 30], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'up'}
09:10:57: [CharacterTools.py:46] [INFO] [Evlape] Converting animation {'offsets': [-50, -31], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'down'}
09:10:57: [CharacterTools.py:46] [INFO] [Evlape] Converting animation {'loop': False, 'offsets': [-10, 14], 'anim': 'singLEFT', 'fps': 24, 'name': 'left', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Evlape] Converting animation {'loop': False, 'offsets': [-110, -5], 'anim': 'singRIGHT', 'fps': 24, 'name': 'right', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Evlape successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/evlape.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\headzo.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character headzo.json
09:10:57: [CharacterTools.py:46] [INFO] [Headzo] Converting animation {'offsets': [48, 36], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'up'}
09:10:57: [CharacterTools.py:46] [INFO] [Headzo] Converting animation {'offsets': [20, -52], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'down'}
09:10:57: [CharacterTools.py:46] [INFO] [Headzo] Converting animation {'offsets': [48, 3], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'left'}
09:10:57: [CharacterTools.py:46] [INFO] [Headzo] Converting animation {'loop': False, 'offsets': [-53, -18], 'anim': 'singRIGHT', 'fps': 24, 'name': 'right', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Headzo] Converting animation {'offsets': [0, 0], 'indices': [], 'fps': 24, 'anim': 'idle', 'loop': False, 'name': 'HEADZO'}
09:10:57: [CharacterTools.py:51] [INFO] Character Headzo successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/headzo.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\image.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character image.json
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [120, 120], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], 'name': 'image up'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [120, 120], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], 'name': 'image right'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [120, 120], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], 'name': 'image down'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [120, 120], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], 'name': 'image left'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [120, 120], 'loop': True, 'fps': 24, 'anim': 'idle', 'indices': [0, 1], 'name': 'image idle'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [310, 160], 'loop': False, 'fps': 24, 'anim': 'singUP-alt', 'indices': [], 'name': 'image up-alt'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [300, 160], 'loop': False, 'fps': 24, 'anim': 'singDOWN-alt', 'indices': [], 'name': 'image down-alt'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [300, 160], 'loop': False, 'fps': 24, 'anim': 'singLEFT-alt', 'indices': [], 'name': 'image left-alt'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [301, 160], 'loop': True, 'fps': 24, 'anim': 'idle-alt', 'indices': [], 'name': 'image idle-alt'}
09:10:57: [CharacterTools.py:46] [INFO] [Image] Converting animation {'offsets': [311, 160], 'loop': False, 'fps': 24, 'anim': 'singRIGHT-alt', 'indices': [], 'name': 'image right-alt'}
09:10:57: [CharacterTools.py:51] [INFO] Character Image successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/image.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\invisible-place.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character invisible-place.json
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': 'req', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'offsets': [0, -14], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [], 'name': 'rughpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'offsets': [110, 10], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'leftpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'offsets': [0, 20], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'upppose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'offsets': [-10, -60], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'downpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible Place] Converting animation {'loop': False, 'offsets': [184, 591], 'anim': 'drop', 'fps': 24, 'name': 'drop', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Invisible Place successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/invisible-place.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\invisible.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character invisible.json
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': 'req', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'offsets': [0, -14], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [], 'name': 'rughpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'offsets': [110, 10], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'leftpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'offsets': [0, 20], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'upppose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'offsets': [-10, -60], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'downpose'}
09:10:57: [CharacterTools.py:46] [INFO] [Invisible] Converting animation {'loop': False, 'offsets': [184, 591], 'anim': 'drop', 'fps': 24, 'name': 'drop', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Invisible successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/invisible.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\jank.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character jank.json
09:10:57: [CharacterTools.py:46] [INFO] [Jank] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'Jankeest'}
09:10:57: [CharacterTools.py:46] [INFO] [Jank] Converting animation {'offsets': [80, -51], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'jankdown'}
09:10:57: [CharacterTools.py:46] [INFO] [Jank] Converting animation {'offsets': [72, 284], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'jankup'}
09:10:57: [CharacterTools.py:46] [INFO] [Jank] Converting animation {'offsets': [40, -6], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'jankleft'}
09:10:57: [CharacterTools.py:46] [INFO] [Jank] Converting animation {'offsets': [-20, -45], 'indices': [], 'fps': 24, 'anim': 'singRIGHT', 'loop': True, 'name': 'jankwalking'}
09:10:57: [CharacterTools.py:51] [INFO] Character Jank successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/jank.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\johndoe.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character johndoe.json
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'jon'}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'offsets': [-30, 35], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'johnup'}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'offsets': [0, -71], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'johndown'}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'offsets': [50, -7], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'johnleft'}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'offsets': [10, 29], 'loop': False, 'fps': 24, 'anim': 'kill', 'indices': [], 'name': 'johntransiiton'}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'loop': False, 'offsets': [10, 90], 'anim': 'singUP-alt', 'fps': 24, 'name': 'john2up', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'loop': False, 'offsets': [-60, 50], 'anim': 'singRIGHT-alt', 'fps': 24, 'name': 'john2right', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'loop': False, 'offsets': [140, 20], 'anim': 'singLEFT-alt', 'fps': 24, 'name': 'john2left', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'loop': False, 'offsets': [130, -70], 'anim': 'singDOWN-alt', 'fps': 24, 'name': 'john2down', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoe] Converting animation {'loop': False, 'offsets': [-23, -18], 'anim': 'singRIGHT', 'fps': 24, 'name': 'johnright', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Johndoe successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/johndoe.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\johndoeevil.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character johndoeevil.json
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': '3idle', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [-10, 50], 'anim': 'singUP', 'fps': 24, 'name': 'jonerup', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [50, 9], 'anim': 'singDOWN', 'fps': 24, 'name': 'jonerdown', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [107, -18], 'anim': 'singRIGHT', 'fps': 24, 'name': 'jonerleft', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [11, -50], 'anim': 'singLEFT', 'fps': 24, 'name': 'jonerright', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Johndoeevil] Converting animation {'loop': False, 'offsets': [7, 13], 'anim': 'kill', 'fps': 24, 'name': 'johntransiiton', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Johndoeevil successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/johndoeevil.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\krollge.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character krollge.json
09:10:57: [CharacterTools.py:46] [INFO] [Krollge] Converting animation {'offsets': [1, 0], 'indices': [], 'fps': 12, 'anim': 'idle', 'loop': False, 'name': 'krollge idle'}
09:10:57: [CharacterTools.py:46] [INFO] [Krollge] Converting animation {'offsets': [0, 0], 'indices': [], 'fps': 12, 'anim': 'singLEFT', 'loop': False, 'name': 'krollge left'}
09:10:57: [CharacterTools.py:46] [INFO] [Krollge] Converting animation {'offsets': [0, 0], 'indices': [], 'fps': 12, 'anim': 'singUP', 'loop': False, 'name': 'krollge up'}
09:10:57: [CharacterTools.py:46] [INFO] [Krollge] Converting animation {'offsets': [3, 0], 'indices': [], 'fps': 12, 'anim': 'singRIGHT', 'loop': False, 'name': 'krollge right'}
09:10:57: [CharacterTools.py:46] [INFO] [Krollge] Converting animation {'offsets': [0, 0], 'indices': [], 'fps': 12, 'anim': 'singDOWN', 'loop': False, 'name': 'krollge down'}
09:10:57: [CharacterTools.py:51] [INFO] Character Krollge successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/krollge.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\lexrbx.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character lexrbx.json
09:10:57: [CharacterTools.py:46] [INFO] [Lexrbx] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'IDLE'}
09:10:57: [CharacterTools.py:46] [INFO] [Lexrbx] Converting animation {'offsets': [-28, 25], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'UP'}
09:10:57: [CharacterTools.py:46] [INFO] [Lexrbx] Converting animation {'offsets': [-17, -38], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'DOWN'}
09:10:57: [CharacterTools.py:46] [INFO] [Lexrbx] Converting animation {'offsets': [-9, -17], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'LEFT'}
09:10:57: [CharacterTools.py:46] [INFO] [Lexrbx] Converting animation {'loop': False, 'offsets': [-54, -18], 'anim': 'singRIGHT', 'fps': 24, 'name': 'RIGHT', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Lexrbx successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/lexrbx.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\mimirbx.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character mimirbx.json
09:10:57: [CharacterTools.py:46] [INFO] [Mimirbx] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'IDLE'}
09:10:57: [CharacterTools.py:46] [INFO] [Mimirbx] Converting animation {'offsets': [-20, 55], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'UP'}
09:10:57: [CharacterTools.py:46] [INFO] [Mimirbx] Converting animation {'offsets': [-15, -89], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'DOWN'}
09:10:57: [CharacterTools.py:46] [INFO] [Mimirbx] Converting animation {'offsets': [11, -37], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'LEFT'}
09:10:57: [CharacterTools.py:46] [INFO] [Mimirbx] Converting animation {'loop': False, 'offsets': [-45, 4], 'anim': 'singRIGHT', 'fps': 24, 'name': 'RIGHT', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Mimirbx successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/mimirbx.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\none.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character none.json
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-5, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'BF idle dance'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [5, -6], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'BF NOTE LEFT0'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-10, -50], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'BF NOTE DOWN0'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-29, 27], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'BF NOTE UP0'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-48, -7], 'loop': False, 'fps': 24, 'anim': 'singRIGHT', 'indices': [], 'name': 'BF NOTE RIGHT0'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [7, 19], 'loop': False, 'fps': 24, 'anim': 'singLEFTmiss', 'indices': [], 'name': 'BF NOTE LEFT MISS'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-15, -19], 'loop': False, 'fps': 24, 'anim': 'singDOWNmiss', 'indices': [], 'name': 'BF NOTE DOWN MISS'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-36, 27], 'loop': False, 'fps': 24, 'anim': 'singUPmiss', 'indices': [], 'name': 'BF NOTE UP MISS'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-44, 22], 'loop': False, 'fps': 24, 'anim': 'singRIGHTmiss', 'indices': [], 'name': 'BF NOTE RIGHT MISS'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-3, 5], 'loop': False, 'fps': 24, 'anim': 'hey', 'indices': [], 'name': 'BF HEY'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [15, 18], 'loop': False, 'fps': 24, 'anim': 'hurt', 'indices': [], 'name': 'BF hit'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-4, 0], 'loop': True, 'fps': 24, 'anim': 'scared', 'indices': [], 'name': 'BF idle shaking'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [37, 11], 'loop': False, 'fps': 24, 'anim': 'firstDeath', 'indices': [], 'name': 'BF dies'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [37, 5], 'loop': True, 'fps': 24, 'anim': 'deathLoop', 'indices': [], 'name': 'BF Dead Loop'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [37, 69], 'loop': False, 'fps': 24, 'anim': 'deathConfirm', 'indices': [], 'name': 'BF Dead confirm'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-10, -16], 'loop': False, 'fps': 24, 'anim': 'dodge', 'indices': [], 'name': 'boyfriend dodge'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [294, 267], 'loop': False, 'fps': 24, 'anim': 'attack', 'indices': [], 'name': 'boyfriend attack'}
09:10:57: [CharacterTools.py:46] [INFO] [None] Converting animation {'offsets': [-40, -40], 'loop': False, 'fps': 24, 'anim': 'pre-attack', 'indices': [], 'name': 'bf pre attack'}
09:10:57: [CharacterTools.py:51] [INFO] Character None successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/none.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\oliver.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character oliver.json
09:10:57: [CharacterTools.py:46] [INFO] [Oliver] Converting animation {'offsets': [0, 10], 'indices': [], 'fps': 30, 'anim': 'idle', 'loop': False, 'name': 'oliver idle'}
09:10:57: [CharacterTools.py:46] [INFO] [Oliver] Converting animation {'offsets': [0, 30], 'indices': [], 'fps': 30, 'anim': 'singUP', 'loop': False, 'name': 'oliver up'}
09:10:57: [CharacterTools.py:46] [INFO] [Oliver] Converting animation {'offsets': [84, 11], 'indices': [], 'fps': 30, 'anim': 'singLEFT', 'loop': False, 'name': 'oliver left'}
09:10:57: [CharacterTools.py:46] [INFO] [Oliver] Converting animation {'offsets': [-10, 10], 'indices': [], 'fps': 30, 'anim': 'singDOWN', 'loop': False, 'name': 'oliver down'}
09:10:57: [CharacterTools.py:46] [INFO] [Oliver] Converting animation {'offsets': [-70, 10], 'indices': [], 'fps': 30, 'anim': 'singRIGHT', 'loop': False, 'name': 'oliver right'}
09:10:57: [CharacterTools.py:51] [INFO] Character Oliver successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/oliver.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\RBLXCYC.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character RBLXCYC.json
09:10:57: [CharacterTools.py:46] [INFO] [Rblxcyc] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': 'IDLE', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Rblxcyc] Converting animation {'loop': False, 'offsets': [27, -23], 'anim': 'singLEFT', 'fps': 24, 'name': 'LEFT', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Rblxcyc] Converting animation {'loop': False, 'offsets': [25, -35], 'anim': 'singDOWN', 'fps': 24, 'name': 'DOWN', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Rblxcyc] Converting animation {'loop': False, 'offsets': [0, 13], 'anim': 'singUP', 'fps': 24, 'name': 'UP', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Rblxcyc] Converting animation {'loop': False, 'offsets': [-28, -6], 'anim': 'singRIGHT', 'fps': 24, 'name': 'RIGHT', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Rblxcyc successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/RBLXCYC.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\readme.txt is a file...
09:10:57: [main.py:192] [WARNING] D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\readme.txt is a directory, or not a json! Skipped
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\smokeyrbx.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character smokeyrbx.json
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'offsets': [0, 0], 'loop': False, 'fps': 24, 'anim': 'idle', 'indices': [], 'name': 'IDLE'}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'offsets': [-70, -35], 'loop': False, 'fps': 24, 'anim': 'singUP', 'indices': [], 'name': 'UP'}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'offsets': [-75, -112], 'loop': False, 'fps': 24, 'anim': 'singDOWN', 'indices': [], 'name': 'DOWN'}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'offsets': [-19, -97], 'loop': False, 'fps': 24, 'anim': 'singLEFT', 'indices': [], 'name': 'LEFT'}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'loop': False, 'offsets': [-93, -68], 'anim': 'singRIGHT', 'fps': 24, 'name': 'RIGHT', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'loop': False, 'offsets': [-53, -68], 'anim': 'singLEFTmiss', 'fps': 24, 'name': 'MISS', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'loop': False, 'offsets': [-53, -68], 'anim': 'singRIGHTmiss', 'fps': 24, 'name': 'MISS', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'loop': False, 'offsets': [-53, -68], 'anim': 'singDOWNmiss', 'fps': 24, 'name': 'MISS', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Smokeyrbx] Converting animation {'loop': False, 'offsets': [-53, -68], 'anim': 'singUPmiss', 'fps': 24, 'name': 'MISS', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Smokeyrbx successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/smokeyrbx.json
09:10:57: [main.py:185] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/characters\zomb.json is a file...
09:10:57: [CharacterTools.py:26] [INFO] Converting character zomb.json
09:10:57: [CharacterTools.py:46] [INFO] [Zomb] Converting animation {'loop': False, 'offsets': [0, 0], 'anim': 'idle', 'fps': 24, 'name': 'alienidle', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Zomb] Converting animation {'loop': False, 'offsets': [46, 74], 'anim': 'singUP', 'fps': 24, 'name': 'alienup', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Zomb] Converting animation {'loop': False, 'offsets': [40, -51], 'anim': 'singDOWN', 'fps': 24, 'name': 'aliendown', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Zomb] Converting animation {'loop': False, 'offsets': [-100, -5], 'anim': 'singRIGHT', 'fps': 24, 'name': 'alienright', 'indices': []}
09:10:57: [CharacterTools.py:46] [INFO] [Zomb] Converting animation {'loop': False, 'offsets': [100, -11], 'anim': 'singLEFT', 'fps': 24, 'name': 'alienleft', 'indices': []}
09:10:57: [CharacterTools.py:51] [INFO] Character Zomb successfully converted
09:10:57: [CharacterTools.py:56] [INFO] Character None saved to C:/Users/willi/Downloads/funkin-windows-64bit/mods/17Boo/data/characters/zomb.json
09:10:57: [main.py:197] [INFO] Copying character icons...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/icons/*
09:10:57: [main.py:207] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/icons\icon-666.png
09:10:57: [main.py:207] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/icons\icon-jon.png
09:10:57: [main.py:207] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/icons\icon-kevin.png
09:10:57: [main.py:207] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/icons\icon-pk.png
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs/*
09:10:57: [main.py:236] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute is a valid song directory...
09:10:57: [main.py:238] [INFO] Copying files in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute/*
09:10:57: [main.py:241] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute\Inst.ogg
09:10:57: [main.py:311] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute\Voices.ogg
09:10:57: [main.py:311] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute\Voicesopp.ogg
09:10:57: [main.py:311] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\66cute\Voicesplay.ogg
09:10:57: [main.py:236] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\joner is a valid song directory...
09:10:57: [main.py:238] [INFO] Copying files in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\joner
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\joner/*
09:10:57: [main.py:241] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\joner\Inst.ogg
09:10:57: [main.py:311] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\joner\Voices.ogg
09:10:57: [main.py:236] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\ogg is a valid song directory...
09:10:57: [main.py:238] [INFO] Copying files in D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\ogg
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\ogg/*
09:10:57: [main.py:241] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\ogg\Inst.ogg
09:10:57: [main.py:311] [INFO] Copying asset D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\ogg\Voices.ogg
09:10:57: [main.py:236] [INFO] Checking if D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/songs\readme.txt is a valid song directory...
09:10:57: [main.py:327] [INFO] Converting weeks (levels)...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/weeks/*.json
09:10:57: [main.py:336] [INFO] Loading D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/weeks\testing.json into the converter...
09:10:57: [WeekTools.py:21] [INFO] Opening .json
09:10:57: [WeekTools.py:25] [ERROR] Could not open .json
09:10:57: [WeekTools.py:21] [INFO] Opening .json
09:10:57: [WeekTools.py:25] [ERROR] Could not open .json
09:10:57: [WeekTools.py:21] [INFO] Opening .json
09:10:57: [WeekTools.py:25] [ERROR] Could not open .json
09:10:57: [main.py:342] [INFO] Copying prop assets...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/menucharacters/*.xml
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/menucharacters/*.png
09:10:57: [main.py:360] [INFO] Copying level titles...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/images/storymenu/*.png
09:10:57: [main.py:377] [INFO] Converting stages...
09:10:57: [files.py:12] [INFO] Finding all files or directories with glob: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/stages/*.json
09:10:57: [main.py:385] [INFO] Converting D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/stages\dummy.json
09:10:57: [main.py:391] [INFO] Parsing .lua with matching .json name: D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/stages\dummy.lua
09:10:57: [main.py:395] [INFO] Parsing D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/stages\dummy.lua and attempting to extract methods and calls
09:10:57: [StageLuaParse.py:71] [INFO] Getting props of onCreatePost
09:10:57: [main.py:401] [INFO] Converting Stage JSON
09:10:57: [main.py:385] [INFO] Converting D:/1downloads/psychengine-windows-0.7.1/PsychEngine/mods/17Boo/stages\home.json

### What are the contents of your mod folder? (if applicable)

its got all the folders it needs, but looking in the folders, it's missing the pictures of the stages or any parts of them. the game does try to load the stages, but it throws an error.

### Additional Context (if applicable)

The mod seems to have actually been ported fine, none of the stages loaded and characters only loaded in the song joner

**Comment by gusborg88** [comment]
what error did the game make? I think fnf has a logs folder now that you can check, i forgot. Also, i think this was fixed recently, maybe download a new build from the actions page.

**Comment by Willio2000** [comment]
the error that came from the game was it trying to load the stages, but it couldnt load the stages, because the images for the stages were missing
ill check the new build and see if it does anything

**Comment by Willio2000** [comment]
the images of the stages are still missing, so the stages still don't load correctly.
but the porter didnt crash this time
